name: image_cropper_example
description: Demonstrates how to use the flutter_image_cropper plugin.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.5.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  cupertino_icons: ^1.0.4
  dotted_border: ^2.1.0
  image_cropper:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
